In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/processed/processed-without-impute.csv",index_col=0)

In [3]:
df.head()

,Vehicle Category,GVWR Class,Fuel Type,Model Year,Fuel Technology,Electric Mile Range,Number of Vehicles Registered at the Same Address,Vehicle Population
Date,,,,,,,,
2019,P,Not Applicable,Gasoline,2020,ICE,Not Applicable,≥4,395883
2020,P,Not Applicable,Gasoline,2020,ICE,Not Applicable,1,370954
2021,P,Not Applicable,Gasoline,2020,ICE,Not Applicable,1,349406
2019,P,Not Applicable,Gasoline,2019,ICE,Not Applicable,≥4,348475
2019,P,Not Applicable,Gasoline,2018,ICE,Not Applicable,≥4,333296

In [4]:
df_encoded = pd.get_dummies(df, columns=['Vehicle Category', 'Fuel Type', 'Fuel Technology'], drop_first=True)

In [5]:
# Define mappings for ordinal encoding
mile_range_mapping = {
    'Not Applicable': 0,
    '0 to 50 miles': 1,
    '51 to 100 miles': 2,
    '101 to 150 miles': 3,
    '>150 miles': 4,
    'Unknown': -1
}

vehicle_count_mapping = {
    '1': 1,
    '2': 2,
    '3': 3,
    '≥4': 4,
    'Unknown': -1
}

# Apply ordinal encoding
df_encoded['Electric Mile Range'] = df['Electric Mile Range'].map(mile_range_mapping)
df_encoded['Number of Vehicles Registered at the Same Address'] = df['Number of Vehicles Registered at the Same Address'].map(vehicle_count_mapping)

In [6]:
gvwr_mapping = {
    'Not Applicable': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    'Unknown': -1
}

df_encoded['GVWR Class'] = df['GVWR Class'].map(gvwr_mapping)

In [7]:
df_encoded.head()

,GVWR Class,Model Year,Electric Mile Range,Number of Vehicles Registered at the Same Address,Vehicle Population,Vehicle Category_BS,Vehicle Category_BT,Vehicle Category_MC,Vehicle Category_MH,Vehicle Category_P,...,Vehicle Category_T6,Vehicle Category_T7,Fuel Type_Electric,Fuel Type_Gasoline,Fuel Type_Hydrogen,Fuel Type_Natural Gas,Fuel Type_Unknown,Fuel Technology_FCEV,Fuel Technology_ICE,Fuel Technology_PHEV
Date,,,,,,,,,,,,,,,,,,,,,
2019,0,2020,0,4,395883,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2020,0,2020,0,1,370954,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2021,0,2020,0,1,349406,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2019,0,2019,0,4,348475,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2019,0,2018,0,4,333296,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False

In [8]:
df_encoded.columns

Index(['GVWR Class', 'Model Year', 'Electric Mile Range',
       'Number of Vehicles Registered at the Same Address',
       'Vehicle Population', 'Vehicle Category_BS', 'Vehicle Category_BT',
       'Vehicle Category_MC', 'Vehicle Category_MH', 'Vehicle Category_P',
       'Vehicle Category_T1', 'Vehicle Category_T2', 'Vehicle Category_T3',
       'Vehicle Category_T4', 'Vehicle Category_T5', 'Vehicle Category_T6',
       'Vehicle Category_T7', 'Fuel Type_Electric', 'Fuel Type_Gasoline',
       'Fuel Type_Hydrogen', 'Fuel Type_Natural Gas', 'Fuel Type_Unknown',
       'Fuel Technology_FCEV', 'Fuel Technology_ICE', 'Fuel Technology_PHEV'],
      dtype='object')

In [9]:
df_encoded.to_csv("../data/processed/encoded_dataset-non-impute.csv")

In [10]:
df_encoded

,GVWR Class,Model Year,Electric Mile Range,Number of Vehicles Registered at the Same Address,Vehicle Population,Vehicle Category_BS,Vehicle Category_BT,Vehicle Category_MC,Vehicle Category_MH,Vehicle Category_P,...,Vehicle Category_T6,Vehicle Category_T7,Fuel Type_Electric,Fuel Type_Gasoline,Fuel Type_Hydrogen,Fuel Type_Natural Gas,Fuel Type_Unknown,Fuel Technology_FCEV,Fuel Technology_ICE,Fuel Technology_PHEV
Date,,,,,,,,,,,,,,,,,,,,,
2019,0,2020,0,4,395883,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2020,0,2020,0,1,370954,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2021,0,2020,0,1,349406,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2019,0,2019,0,4,348475,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
2019,0,2018,0,4,333296,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0,1983,0,1,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2019,0,1980,0,2,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2019,0,1978,0,3,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2019,0,1976,0,2,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2019,0,1976,0,3,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False